development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
<<<<<<< HEAD
  channel_prefix: contatos_production
=======
  channel_prefix: ZSSN_API_production
>>>>>>> ba6bb8fbeb30cb9633f1beda48e41980567ab327
